package replay

// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

import (
	encoding_json "encoding/json"
	__iso_option "github.com/IBM/fp-go/v2/optics/iso/option"
	__lens "github.com/IBM/fp-go/v2/optics/lens"
	__lens_option "github.com/IBM/fp-go/v2/optics/lens/option"
	__prism "github.com/IBM/fp-go/v2/optics/prism"
	__option "github.com/IBM/fp-go/v2/option"
	time "time"
)

// RecordLenses provides [lenses] for accessing fields of [Record]
//
// [lenses]: __lens.Lens
type RecordLenses struct {
	// Ts is a [__lens.Lens] for the Ts field of [Record]
	Ts __lens.Lens[Record, time.Time]
	// Level is a [__lens.Lens] for the Level field of [Record]
	Level __lens.Lens[Record, string]
	// Module is a [__lens.Lens] for the Module field of [Record]
	Module __lens.Lens[Record, string]
	// Msg is a [__lens.Lens] for the Msg field of [Record]
	Msg __lens.Lens[Record, string]
	// TaskID is a [__lens.Lens] for the TaskID field of [Record]
	TaskID __lens.Lens[Record, string]
	// Data is a [__lens.Lens] for the Data field of [Record]
	Data __lens.Lens[Record, encoding_json.RawMessage]
	// LevelO is a [__lens_option.LensO] for the Level field of [Record], treating the zero value as absent
	LevelO __lens_option.LensO[Record, string]
	// ModuleO is a [__lens_option.LensO] for the Module field of [Record], treating the zero value as absent
	ModuleO __lens_option.LensO[Record, string]
	// MsgO is a [__lens_option.LensO] for the Msg field of [Record], treating the zero value as absent
	MsgO __lens_option.LensO[Record, string]
	// TaskIDO is a [__lens_option.LensO] for the TaskID field of [Record], treating the zero value as absent
	TaskIDO __lens_option.LensO[Record, string]
}

// RecordRefLenses provides [lenses] for accessing fields of [Record] via a pointer to [Record]
//
// [lenses]: __lens.Lens
type RecordRefLenses struct {
	// Ts is a [__lens.Lens] for the Ts field of [Record] via a pointer receiver
	Ts __lens.Lens[*Record, time.Time]
	// Level is a [__lens.Lens] for the Level field of [Record] via a pointer receiver
	Level __lens.Lens[*Record, string]
	// Module is a [__lens.Lens] for the Module field of [Record] via a pointer receiver
	Module __lens.Lens[*Record, string]
	// Msg is a [__lens.Lens] for the Msg field of [Record] via a pointer receiver
	Msg __lens.Lens[*Record, string]
	// TaskID is a [__lens.Lens] for the TaskID field of [Record] via a pointer receiver
	TaskID __lens.Lens[*Record, string]
	// Data is a [__lens.Lens] for the Data field of [Record] via a pointer receiver
	Data __lens.Lens[*Record, encoding_json.RawMessage]
	// LevelO is a [__lens_option.LensO] for the Level field of [Record] via a pointer receiver, treating the zero value as absent
	LevelO __lens_option.LensO[*Record, string]
	// ModuleO is a [__lens_option.LensO] for the Module field of [Record] via a pointer receiver, treating the zero value as absent
	ModuleO __lens_option.LensO[*Record, string]
	// MsgO is a [__lens_option.LensO] for the Msg field of [Record] via a pointer receiver, treating the zero value as absent
	MsgO __lens_option.LensO[*Record, string]
	// TaskIDO is a [__lens_option.LensO] for the TaskID field of [Record] via a pointer receiver, treating the zero value as absent
	TaskIDO __lens_option.LensO[*Record, string]
}

// RecordPrisms provides [prisms] for accessing fields of [Record]
//
// [prisms]: __prism.Prism
type RecordPrisms struct {
	// Ts is a [__prism.Prism] for the Ts field of [Record]
	Ts __prism.Prism[Record, time.Time]
	// Level is a [__prism.Prism] for the Level field of [Record]
	Level __prism.Prism[Record, string]
	// Module is a [__prism.Prism] for the Module field of [Record]
	Module __prism.Prism[Record, string]
	// Msg is a [__prism.Prism] for the Msg field of [Record]
	Msg __prism.Prism[Record, string]
	// TaskID is a [__prism.Prism] for the TaskID field of [Record]
	TaskID __prism.Prism[Record, string]
	// Data is a [__prism.Prism] for the Data field of [Record]
	Data __prism.Prism[Record, encoding_json.RawMessage]
}

// RecordRefPrisms provides [prisms] for accessing fields of [Record] via a pointer to [Record]
//
// [prisms]: __prism.Prism
type RecordRefPrisms struct {
	// Ts is a [__prism.Prism] for the Ts field of [Record] via a pointer receiver
	Ts __prism.Prism[*Record, time.Time]
	// Level is a [__prism.Prism] for the Level field of [Record] via a pointer receiver
	Level __prism.Prism[*Record, string]
	// Module is a [__prism.Prism] for the Module field of [Record] via a pointer receiver
	Module __prism.Prism[*Record, string]
	// Msg is a [__prism.Prism] for the Msg field of [Record] via a pointer receiver
	Msg __prism.Prism[*Record, string]
	// TaskID is a [__prism.Prism] for the TaskID field of [Record] via a pointer receiver
	TaskID __prism.Prism[*Record, string]
	// Data is a [__prism.Prism] for the Data field of [Record] via a pointer receiver
	Data __prism.Prism[*Record, encoding_json.RawMessage]
}

// MakeRecordTsLens returns a [__lens.Lens] for the Ts field of [Record]
func MakeRecordTsLens() __lens.Lens[Record, time.Time] {
	return __lens.MakeLensWithName(
		func(s Record) time.Time { return s.Ts },
		func(s Record, v time.Time) Record { s.Ts = v; return s },
		"Record.Ts",
	)
}

// MakeRecordTsRefLens returns a [__lens.Lens] for the Ts field of [Record] via a pointer receiver
func MakeRecordTsRefLens() __lens.Lens[*Record, time.Time] {
	return __lens.MakeLensRefWithName(
		func(s *Record) time.Time { return s.Ts },
		func(s *Record, v time.Time) *Record { s.Ts = v; return s },
		"(*Record).Ts",
	)
}

// MakeRecordTsPrism returns a [__prism.Prism] for the Ts field of [Record]
func MakeRecordTsPrism() __prism.Prism[Record, time.Time] {
	return __prism.MakePrismWithName(
		func(s Record) __option.Option[time.Time] { return __option.Some(s.Ts) },
		func(v time.Time) Record {
			return Record{Ts: v}
		},
		"Record.Ts",
	)
}

// MakeRecordTsRefPrism returns a [__prism.Prism] for the Ts field of [Record] via a pointer receiver
func MakeRecordTsRefPrism() __prism.Prism[*Record, time.Time] {
	return __prism.MakePrismWithName(
		func(s *Record) __option.Option[time.Time] { return __option.Some(s.Ts) },
		func(v time.Time) *Record {
			return &Record{Ts: v}
		},
		"Record.Ts",
	)
}

// MakeRecordLevelLens returns a [__lens.Lens] for the Level field of [Record]
func MakeRecordLevelLens() __lens.Lens[Record, string] {
	return __lens.MakeLensWithName(
		func(s Record) string { return s.Level },
		func(s Record, v string) Record { s.Level = v; return s },
		"Record.Level",
	)
}

// MakeRecordLevelLensO returns a [__lens_option.LensO] for the Level field of [Record]
func MakeRecordLevelLensO() __lens_option.LensO[Record, string] {
	return __lens_option.FromIso[Record](__iso_option.FromZero[string]())(MakeRecordLevelLens())
}

// MakeRecordLevelRefLens returns a [__lens.Lens] for the Level field of [Record] via a pointer receiver
func MakeRecordLevelRefLens() __lens.Lens[*Record, string] {
	return __lens.MakeLensStrictWithName(
		func(s *Record) string { return s.Level },
		func(s *Record, v string) *Record { s.Level = v; return s },
		"(*Record).Level",
	)
}

// MakeRecordLevelRefLensO returns a [__lens_option.LensO] for the Level field of [Record] via a pointer receiver
func MakeRecordLevelRefLensO() __lens_option.LensO[*Record, string] {
	return __lens_option.FromIso[*Record](__iso_option.FromZero[string]())(MakeRecordLevelRefLens())
}

// MakeRecordLevelPrism returns a [__prism.Prism] for the Level field of [Record]
func MakeRecordLevelPrism() __prism.Prism[Record, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s Record) __option.Option[string] { return _fromNonZero(s.Level) },
		func(v string) Record {
			return Record{Level: v}
		},
		"Record.Level",
	)
}

// MakeRecordLevelRefPrism returns a [__prism.Prism] for the Level field of [Record] via a pointer receiver
func MakeRecordLevelRefPrism() __prism.Prism[*Record, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s *Record) __option.Option[string] { return _fromNonZero(s.Level) },
		func(v string) *Record {
			return &Record{Level: v}
		},
		"Record.Level",
	)
}

// MakeRecordModuleLens returns a [__lens.Lens] for the Module field of [Record]
func MakeRecordModuleLens() __lens.Lens[Record, string] {
	return __lens.MakeLensWithName(
		func(s Record) string { return s.Module },
		func(s Record, v string) Record { s.Module = v; return s },
		"Record.Module",
	)
}

// MakeRecordModuleLensO returns a [__lens_option.LensO] for the Module field of [Record]
func MakeRecordModuleLensO() __lens_option.LensO[Record, string] {
	return __lens_option.FromIso[Record](__iso_option.FromZero[string]())(MakeRecordModuleLens())
}

// MakeRecordModuleRefLens returns a [__lens.Lens] for the Module field of [Record] via a pointer receiver
func MakeRecordModuleRefLens() __lens.Lens[*Record, string] {
	return __lens.MakeLensStrictWithName(
		func(s *Record) string { return s.Module },
		func(s *Record, v string) *Record { s.Module = v; return s },
		"(*Record).Module",
	)
}

// MakeRecordModuleRefLensO returns a [__lens_option.LensO] for the Module field of [Record] via a pointer receiver
func MakeRecordModuleRefLensO() __lens_option.LensO[*Record, string] {
	return __lens_option.FromIso[*Record](__iso_option.FromZero[string]())(MakeRecordModuleRefLens())
}

// MakeRecordModulePrism returns a [__prism.Prism] for the Module field of [Record]
func MakeRecordModulePrism() __prism.Prism[Record, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s Record) __option.Option[string] { return _fromNonZero(s.Module) },
		func(v string) Record {
			return Record{Module: v}
		},
		"Record.Module",
	)
}

// MakeRecordModuleRefPrism returns a [__prism.Prism] for the Module field of [Record] via a pointer receiver
func MakeRecordModuleRefPrism() __prism.Prism[*Record, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s *Record) __option.Option[string] { return _fromNonZero(s.Module) },
		func(v string) *Record {
			return &Record{Module: v}
		},
		"Record.Module",
	)
}

// MakeRecordMsgLens returns a [__lens.Lens] for the Msg field of [Record]
func MakeRecordMsgLens() __lens.Lens[Record, string] {
	return __lens.MakeLensWithName(
		func(s Record) string { return s.Msg },
		func(s Record, v string) Record { s.Msg = v; return s },
		"Record.Msg",
	)
}

// MakeRecordMsgLensO returns a [__lens_option.LensO] for the Msg field of [Record]
func MakeRecordMsgLensO() __lens_option.LensO[Record, string] {
	return __lens_option.FromIso[Record](__iso_option.FromZero[string]())(MakeRecordMsgLens())
}

// MakeRecordMsgRefLens returns a [__lens.Lens] for the Msg field of [Record] via a pointer receiver
func MakeRecordMsgRefLens() __lens.Lens[*Record, string] {
	return __lens.MakeLensStrictWithName(
		func(s *Record) string { return s.Msg },
		func(s *Record, v string) *Record { s.Msg = v; return s },
		"(*Record).Msg",
	)
}

// MakeRecordMsgRefLensO returns a [__lens_option.LensO] for the Msg field of [Record] via a pointer receiver
func MakeRecordMsgRefLensO() __lens_option.LensO[*Record, string] {
	return __lens_option.FromIso[*Record](__iso_option.FromZero[string]())(MakeRecordMsgRefLens())
}

// MakeRecordMsgPrism returns a [__prism.Prism] for the Msg field of [Record]
func MakeRecordMsgPrism() __prism.Prism[Record, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s Record) __option.Option[string] { return _fromNonZero(s.Msg) },
		func(v string) Record {
			return Record{Msg: v}
		},
		"Record.Msg",
	)
}

// MakeRecordMsgRefPrism returns a [__prism.Prism] for the Msg field of [Record] via a pointer receiver
func MakeRecordMsgRefPrism() __prism.Prism[*Record, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s *Record) __option.Option[string] { return _fromNonZero(s.Msg) },
		func(v string) *Record {
			return &Record{Msg: v}
		},
		"Record.Msg",
	)
}

// MakeRecordTaskIDLens returns a [__lens.Lens] for the TaskID field of [Record]
func MakeRecordTaskIDLens() __lens.Lens[Record, string] {
	return __lens.MakeLensWithName(
		func(s Record) string { return s.TaskID },
		func(s Record, v string) Record { s.TaskID = v; return s },
		"Record.TaskID",
	)
}

// MakeRecordTaskIDLensO returns a [__lens_option.LensO] for the TaskID field of [Record]
func MakeRecordTaskIDLensO() __lens_option.LensO[Record, string] {
	return __lens_option.FromIso[Record](__iso_option.FromZero[string]())(MakeRecordTaskIDLens())
}

// MakeRecordTaskIDRefLens returns a [__lens.Lens] for the TaskID field of [Record] via a pointer receiver
func MakeRecordTaskIDRefLens() __lens.Lens[*Record, string] {
	return __lens.MakeLensStrictWithName(
		func(s *Record) string { return s.TaskID },
		func(s *Record, v string) *Record { s.TaskID = v; return s },
		"(*Record).TaskID",
	)
}

// MakeRecordTaskIDRefLensO returns a [__lens_option.LensO] for the TaskID field of [Record] via a pointer receiver
func MakeRecordTaskIDRefLensO() __lens_option.LensO[*Record, string] {
	return __lens_option.FromIso[*Record](__iso_option.FromZero[string]())(MakeRecordTaskIDRefLens())
}

// MakeRecordTaskIDPrism returns a [__prism.Prism] for the TaskID field of [Record]
func MakeRecordTaskIDPrism() __prism.Prism[Record, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s Record) __option.Option[string] { return _fromNonZero(s.TaskID) },
		func(v string) Record {
			return Record{TaskID: v}
		},
		"Record.TaskID",
	)
}

// MakeRecordTaskIDRefPrism returns a [__prism.Prism] for the TaskID field of [Record] via a pointer receiver
func MakeRecordTaskIDRefPrism() __prism.Prism[*Record, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s *Record) __option.Option[string] { return _fromNonZero(s.TaskID) },
		func(v string) *Record {
			return &Record{TaskID: v}
		},
		"Record.TaskID",
	)
}

// MakeRecordDataLens returns a [__lens.Lens] for the Data field of [Record]
func MakeRecordDataLens() __lens.Lens[Record, encoding_json.RawMessage] {
	return __lens.MakeLensWithName(
		func(s Record) encoding_json.RawMessage { return s.Data },
		func(s Record, v encoding_json.RawMessage) Record { s.Data = v; return s },
		"Record.Data",
	)
}

// MakeRecordDataRefLens returns a [__lens.Lens] for the Data field of [Record] via a pointer receiver
func MakeRecordDataRefLens() __lens.Lens[*Record, encoding_json.RawMessage] {
	return __lens.MakeLensRefWithName(
		func(s *Record) encoding_json.RawMessage { return s.Data },
		func(s *Record, v encoding_json.RawMessage) *Record { s.Data = v; return s },
		"(*Record).Data",
	)
}

// MakeRecordDataPrism returns a [__prism.Prism] for the Data field of [Record]
func MakeRecordDataPrism() __prism.Prism[Record, encoding_json.RawMessage] {
	return __prism.MakePrismWithName(
		func(s Record) __option.Option[encoding_json.RawMessage] { return __option.Some(s.Data) },
		func(v encoding_json.RawMessage) Record {
			return Record{Data: v}
		},
		"Record.Data",
	)
}

// MakeRecordDataRefPrism returns a [__prism.Prism] for the Data field of [Record] via a pointer receiver
func MakeRecordDataRefPrism() __prism.Prism[*Record, encoding_json.RawMessage] {
	return __prism.MakePrismWithName(
		func(s *Record) __option.Option[encoding_json.RawMessage] { return __option.Some(s.Data) },
		func(v encoding_json.RawMessage) *Record {
			return &Record{Data: v}
		},
		"Record.Data",
	)
}

// MakeRecordLenses creates a new [RecordLenses] with [lenses] for all fields
//
// [lenses]: __lens.Lens
func MakeRecordLenses() RecordLenses {
	return RecordLenses{
		// mandatory lenses
		Ts:     MakeRecordTsLens(),
		Level:  MakeRecordLevelLens(),
		Module: MakeRecordModuleLens(),
		Msg:    MakeRecordMsgLens(),
		TaskID: MakeRecordTaskIDLens(),
		Data:   MakeRecordDataLens(),
		// optional lenses
		LevelO:  MakeRecordLevelLensO(),
		ModuleO: MakeRecordModuleLensO(),
		MsgO:    MakeRecordMsgLensO(),
		TaskIDO: MakeRecordTaskIDLensO(),
	}
}

// MakeRecordRefLenses creates a new [RecordRefLenses] with [lenses] for all fields via a pointer to [Record]
//
// [lenses]: __lens.Lens
func MakeRecordRefLenses() RecordRefLenses {
	return RecordRefLenses{
		// mandatory lenses
		Ts:     MakeRecordTsRefLens(),
		Level:  MakeRecordLevelRefLens(),
		Module: MakeRecordModuleRefLens(),
		Msg:    MakeRecordMsgRefLens(),
		TaskID: MakeRecordTaskIDRefLens(),
		Data:   MakeRecordDataRefLens(),
		// optional lenses
		LevelO:  MakeRecordLevelRefLensO(),
		ModuleO: MakeRecordModuleRefLensO(),
		MsgO:    MakeRecordMsgRefLensO(),
		TaskIDO: MakeRecordTaskIDRefLensO(),
	}
}

// MakeRecordPrisms creates a new [RecordPrisms] with [prisms] for all fields
//
// [prisms]: __prism.Prism
func MakeRecordPrisms() RecordPrisms {
	return RecordPrisms{
		Ts:     MakeRecordTsPrism(),
		Level:  MakeRecordLevelPrism(),
		Module: MakeRecordModulePrism(),
		Msg:    MakeRecordMsgPrism(),
		TaskID: MakeRecordTaskIDPrism(),
		Data:   MakeRecordDataPrism(),
	}
}

// MakeRecordRefPrisms creates a new [RecordRefPrisms] with [prisms] for all fields via a pointer to [Record]
//
// [prisms]: __prism.Prism
func MakeRecordRefPrisms() RecordRefPrisms {
	return RecordRefPrisms{
		Ts:     MakeRecordTsRefPrism(),
		Level:  MakeRecordLevelRefPrism(),
		Module: MakeRecordModuleRefPrism(),
		Msg:    MakeRecordMsgRefPrism(),
		TaskID: MakeRecordTaskIDRefPrism(),
		Data:   MakeRecordDataRefPrism(),
	}
}
