package tools

// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

import (
	__iso_option "github.com/IBM/fp-go/v2/optics/iso/option"
	__lens "github.com/IBM/fp-go/v2/optics/lens"
	__lens_option "github.com/IBM/fp-go/v2/optics/lens/option"
	__prism "github.com/IBM/fp-go/v2/optics/prism"
	__option "github.com/IBM/fp-go/v2/option"
	github_com_openai_openai_go_v3 "github.com/openai/openai-go/v3"
)

// ChatCompletionMessageFunctionToolCallFunctionLenses provides [lenses] for accessing fields of [ChatCompletionMessageFunctionToolCallFunction]
//
// [lenses]: __lens.Lens
type ChatCompletionMessageFunctionToolCallFunctionLenses struct {
	// Arguments is a [__lens.Lens] for the Arguments field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction]
	Arguments __lens.Lens[github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string]
	// Name is a [__lens.Lens] for the Name field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction]
	Name __lens.Lens[github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string]
	// ArgumentsO is a [__lens_option.LensO] for the Arguments field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction], treating the zero value as absent
	ArgumentsO __lens_option.LensO[github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string]
	// NameO is a [__lens_option.LensO] for the Name field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction], treating the zero value as absent
	NameO __lens_option.LensO[github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string]
}

// ChatCompletionMessageFunctionToolCallFunctionRefLenses provides [lenses] for accessing fields of [ChatCompletionMessageFunctionToolCallFunction] via a pointer to [ChatCompletionMessageFunctionToolCallFunction]
//
// [lenses]: __lens.Lens
type ChatCompletionMessageFunctionToolCallFunctionRefLenses struct {
	// Arguments is a [__lens.Lens] for the Arguments field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction] via a pointer receiver
	Arguments __lens.Lens[*github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string]
	// Name is a [__lens.Lens] for the Name field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction] via a pointer receiver
	Name __lens.Lens[*github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string]
	// ArgumentsO is a [__lens_option.LensO] for the Arguments field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction] via a pointer receiver, treating the zero value as absent
	ArgumentsO __lens_option.LensO[*github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string]
	// NameO is a [__lens_option.LensO] for the Name field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction] via a pointer receiver, treating the zero value as absent
	NameO __lens_option.LensO[*github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string]
}

// ChatCompletionMessageFunctionToolCallFunctionPrisms provides [prisms] for accessing fields of [ChatCompletionMessageFunctionToolCallFunction]
//
// [prisms]: __prism.Prism
type ChatCompletionMessageFunctionToolCallFunctionPrisms struct {
	// Arguments is a [__prism.Prism] for the Arguments field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction]
	Arguments __prism.Prism[github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string]
	// Name is a [__prism.Prism] for the Name field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction]
	Name __prism.Prism[github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string]
}

// ChatCompletionMessageFunctionToolCallFunctionRefPrisms provides [prisms] for accessing fields of [ChatCompletionMessageFunctionToolCallFunction] via a pointer to [ChatCompletionMessageFunctionToolCallFunction]
//
// [prisms]: __prism.Prism
type ChatCompletionMessageFunctionToolCallFunctionRefPrisms struct {
	// Arguments is a [__prism.Prism] for the Arguments field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction] via a pointer receiver
	Arguments __prism.Prism[*github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string]
	// Name is a [__prism.Prism] for the Name field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction] via a pointer receiver
	Name __prism.Prism[*github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string]
}

// MakeChatCompletionMessageFunctionToolCallFunctionArgumentsLens returns a [__lens.Lens] for the Arguments field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction]
func MakeChatCompletionMessageFunctionToolCallFunctionArgumentsLens() __lens.Lens[github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string] {
	return __lens.MakeLensWithName(
		func(s github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction) string {
			return s.Arguments
		},
		func(s github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, v string) github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction {
			s.Arguments = v
			return s
		},
		"github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction.Arguments",
	)
}

// MakeChatCompletionMessageFunctionToolCallFunctionArgumentsLensO returns a [__lens_option.LensO] for the Arguments field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction]
func MakeChatCompletionMessageFunctionToolCallFunctionArgumentsLensO() __lens_option.LensO[github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string] {
	return __lens_option.FromIso[github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction](__iso_option.FromZero[string]())(MakeChatCompletionMessageFunctionToolCallFunctionArgumentsLens())
}

// MakeChatCompletionMessageFunctionToolCallFunctionArgumentsRefLens returns a [__lens.Lens] for the Arguments field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction] via a pointer receiver
func MakeChatCompletionMessageFunctionToolCallFunctionArgumentsRefLens() __lens.Lens[*github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string] {
	return __lens.MakeLensStrictWithName(
		func(s *github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction) string {
			return s.Arguments
		},
		func(s *github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, v string) *github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction {
			s.Arguments = v
			return s
		},
		"(*github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction).Arguments",
	)
}

// MakeChatCompletionMessageFunctionToolCallFunctionArgumentsRefLensO returns a [__lens_option.LensO] for the Arguments field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction] via a pointer receiver
func MakeChatCompletionMessageFunctionToolCallFunctionArgumentsRefLensO() __lens_option.LensO[*github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string] {
	return __lens_option.FromIso[*github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction](__iso_option.FromZero[string]())(MakeChatCompletionMessageFunctionToolCallFunctionArgumentsRefLens())
}

// MakeChatCompletionMessageFunctionToolCallFunctionArgumentsPrism returns a [__prism.Prism] for the Arguments field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction]
func MakeChatCompletionMessageFunctionToolCallFunctionArgumentsPrism() __prism.Prism[github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction) __option.Option[string] {
			return _fromNonZero(s.Arguments)
		},
		func(v string) github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction {
			return github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction{Arguments: v}
		},
		"github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction.Arguments",
	)
}

// MakeChatCompletionMessageFunctionToolCallFunctionArgumentsRefPrism returns a [__prism.Prism] for the Arguments field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction] via a pointer receiver
func MakeChatCompletionMessageFunctionToolCallFunctionArgumentsRefPrism() __prism.Prism[*github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s *github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction) __option.Option[string] {
			return _fromNonZero(s.Arguments)
		},
		func(v string) *github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction {
			return &github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction{Arguments: v}
		},
		"github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction.Arguments",
	)
}

// MakeChatCompletionMessageFunctionToolCallFunctionNameLens returns a [__lens.Lens] for the Name field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction]
func MakeChatCompletionMessageFunctionToolCallFunctionNameLens() __lens.Lens[github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string] {
	return __lens.MakeLensWithName(
		func(s github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction) string {
			return s.Name
		},
		func(s github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, v string) github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction {
			s.Name = v
			return s
		},
		"github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction.Name",
	)
}

// MakeChatCompletionMessageFunctionToolCallFunctionNameLensO returns a [__lens_option.LensO] for the Name field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction]
func MakeChatCompletionMessageFunctionToolCallFunctionNameLensO() __lens_option.LensO[github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string] {
	return __lens_option.FromIso[github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction](__iso_option.FromZero[string]())(MakeChatCompletionMessageFunctionToolCallFunctionNameLens())
}

// MakeChatCompletionMessageFunctionToolCallFunctionNameRefLens returns a [__lens.Lens] for the Name field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction] via a pointer receiver
func MakeChatCompletionMessageFunctionToolCallFunctionNameRefLens() __lens.Lens[*github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string] {
	return __lens.MakeLensStrictWithName(
		func(s *github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction) string {
			return s.Name
		},
		func(s *github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, v string) *github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction {
			s.Name = v
			return s
		},
		"(*github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction).Name",
	)
}

// MakeChatCompletionMessageFunctionToolCallFunctionNameRefLensO returns a [__lens_option.LensO] for the Name field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction] via a pointer receiver
func MakeChatCompletionMessageFunctionToolCallFunctionNameRefLensO() __lens_option.LensO[*github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string] {
	return __lens_option.FromIso[*github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction](__iso_option.FromZero[string]())(MakeChatCompletionMessageFunctionToolCallFunctionNameRefLens())
}

// MakeChatCompletionMessageFunctionToolCallFunctionNamePrism returns a [__prism.Prism] for the Name field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction]
func MakeChatCompletionMessageFunctionToolCallFunctionNamePrism() __prism.Prism[github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction) __option.Option[string] {
			return _fromNonZero(s.Name)
		},
		func(v string) github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction {
			return github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction{Name: v}
		},
		"github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction.Name",
	)
}

// MakeChatCompletionMessageFunctionToolCallFunctionNameRefPrism returns a [__prism.Prism] for the Name field of [github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction] via a pointer receiver
func MakeChatCompletionMessageFunctionToolCallFunctionNameRefPrism() __prism.Prism[*github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s *github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction) __option.Option[string] {
			return _fromNonZero(s.Name)
		},
		func(v string) *github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction {
			return &github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction{Name: v}
		},
		"github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction.Name",
	)
}

// MakeChatCompletionMessageFunctionToolCallFunctionLenses creates a new [ChatCompletionMessageFunctionToolCallFunctionLenses] with [lenses] for all fields
//
// [lenses]: __lens.Lens
func MakeChatCompletionMessageFunctionToolCallFunctionLenses() ChatCompletionMessageFunctionToolCallFunctionLenses {
	return ChatCompletionMessageFunctionToolCallFunctionLenses{
		// mandatory lenses
		Arguments: MakeChatCompletionMessageFunctionToolCallFunctionArgumentsLens(),
		Name:      MakeChatCompletionMessageFunctionToolCallFunctionNameLens(),
		// optional lenses
		ArgumentsO: MakeChatCompletionMessageFunctionToolCallFunctionArgumentsLensO(),
		NameO:      MakeChatCompletionMessageFunctionToolCallFunctionNameLensO(),
	}
}

// MakeChatCompletionMessageFunctionToolCallFunctionRefLenses creates a new [ChatCompletionMessageFunctionToolCallFunctionRefLenses] with [lenses] for all fields via a pointer to [ChatCompletionMessageFunctionToolCallFunction]
//
// [lenses]: __lens.Lens
func MakeChatCompletionMessageFunctionToolCallFunctionRefLenses() ChatCompletionMessageFunctionToolCallFunctionRefLenses {
	return ChatCompletionMessageFunctionToolCallFunctionRefLenses{
		// mandatory lenses
		Arguments: MakeChatCompletionMessageFunctionToolCallFunctionArgumentsRefLens(),
		Name:      MakeChatCompletionMessageFunctionToolCallFunctionNameRefLens(),
		// optional lenses
		ArgumentsO: MakeChatCompletionMessageFunctionToolCallFunctionArgumentsRefLensO(),
		NameO:      MakeChatCompletionMessageFunctionToolCallFunctionNameRefLensO(),
	}
}

// MakeChatCompletionMessageFunctionToolCallFunctionPrisms creates a new [ChatCompletionMessageFunctionToolCallFunctionPrisms] with [prisms] for all fields
//
// [prisms]: __prism.Prism
func MakeChatCompletionMessageFunctionToolCallFunctionPrisms() ChatCompletionMessageFunctionToolCallFunctionPrisms {
	return ChatCompletionMessageFunctionToolCallFunctionPrisms{
		Arguments: MakeChatCompletionMessageFunctionToolCallFunctionArgumentsPrism(),
		Name:      MakeChatCompletionMessageFunctionToolCallFunctionNamePrism(),
	}
}

// MakeChatCompletionMessageFunctionToolCallFunctionRefPrisms creates a new [ChatCompletionMessageFunctionToolCallFunctionRefPrisms] with [prisms] for all fields via a pointer to [ChatCompletionMessageFunctionToolCallFunction]
//
// [prisms]: __prism.Prism
func MakeChatCompletionMessageFunctionToolCallFunctionRefPrisms() ChatCompletionMessageFunctionToolCallFunctionRefPrisms {
	return ChatCompletionMessageFunctionToolCallFunctionRefPrisms{
		Arguments: MakeChatCompletionMessageFunctionToolCallFunctionArgumentsRefPrism(),
		Name:      MakeChatCompletionMessageFunctionToolCallFunctionNameRefPrism(),
	}
}

// ChatCompletionMessageToolCallUnionLenses provides [lenses] for accessing fields of [ChatCompletionMessageToolCallUnion]
//
// [lenses]: __lens.Lens
type ChatCompletionMessageToolCallUnionLenses struct {
	// ID is a [__lens.Lens] for the ID field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion]
	ID __lens.Lens[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string]
	// Function is a [__lens.Lens] for the Function field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion]
	Function __lens.Lens[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction]
	// Type is a [__lens.Lens] for the Type field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion]
	Type __lens.Lens[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string]
	// Custom is a [__lens.Lens] for the Custom field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion]
	Custom __lens.Lens[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, github_com_openai_openai_go_v3.ChatCompletionMessageCustomToolCallCustom]
	// IDO is a [__lens_option.LensO] for the ID field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion], treating the zero value as absent
	IDO __lens_option.LensO[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string]
	// TypeO is a [__lens_option.LensO] for the Type field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion], treating the zero value as absent
	TypeO __lens_option.LensO[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string]
}

// ChatCompletionMessageToolCallUnionRefLenses provides [lenses] for accessing fields of [ChatCompletionMessageToolCallUnion] via a pointer to [ChatCompletionMessageToolCallUnion]
//
// [lenses]: __lens.Lens
type ChatCompletionMessageToolCallUnionRefLenses struct {
	// ID is a [__lens.Lens] for the ID field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion] via a pointer receiver
	ID __lens.Lens[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string]
	// Function is a [__lens.Lens] for the Function field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion] via a pointer receiver
	Function __lens.Lens[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction]
	// Type is a [__lens.Lens] for the Type field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion] via a pointer receiver
	Type __lens.Lens[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string]
	// Custom is a [__lens.Lens] for the Custom field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion] via a pointer receiver
	Custom __lens.Lens[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, github_com_openai_openai_go_v3.ChatCompletionMessageCustomToolCallCustom]
	// IDO is a [__lens_option.LensO] for the ID field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion] via a pointer receiver, treating the zero value as absent
	IDO __lens_option.LensO[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string]
	// TypeO is a [__lens_option.LensO] for the Type field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion] via a pointer receiver, treating the zero value as absent
	TypeO __lens_option.LensO[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string]
}

// ChatCompletionMessageToolCallUnionPrisms provides [prisms] for accessing fields of [ChatCompletionMessageToolCallUnion]
//
// [prisms]: __prism.Prism
type ChatCompletionMessageToolCallUnionPrisms struct {
	// ID is a [__prism.Prism] for the ID field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion]
	ID __prism.Prism[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string]
	// Function is a [__prism.Prism] for the Function field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion]
	Function __prism.Prism[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction]
	// Type is a [__prism.Prism] for the Type field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion]
	Type __prism.Prism[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string]
	// Custom is a [__prism.Prism] for the Custom field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion]
	Custom __prism.Prism[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, github_com_openai_openai_go_v3.ChatCompletionMessageCustomToolCallCustom]
}

// ChatCompletionMessageToolCallUnionRefPrisms provides [prisms] for accessing fields of [ChatCompletionMessageToolCallUnion] via a pointer to [ChatCompletionMessageToolCallUnion]
//
// [prisms]: __prism.Prism
type ChatCompletionMessageToolCallUnionRefPrisms struct {
	// ID is a [__prism.Prism] for the ID field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion] via a pointer receiver
	ID __prism.Prism[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string]
	// Function is a [__prism.Prism] for the Function field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion] via a pointer receiver
	Function __prism.Prism[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction]
	// Type is a [__prism.Prism] for the Type field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion] via a pointer receiver
	Type __prism.Prism[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string]
	// Custom is a [__prism.Prism] for the Custom field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion] via a pointer receiver
	Custom __prism.Prism[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, github_com_openai_openai_go_v3.ChatCompletionMessageCustomToolCallCustom]
}

// MakeChatCompletionMessageToolCallUnionIDLens returns a [__lens.Lens] for the ID field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion]
func MakeChatCompletionMessageToolCallUnionIDLens() __lens.Lens[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string] {
	return __lens.MakeLensWithName(
		func(s github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion) string { return s.ID },
		func(s github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, v string) github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion {
			s.ID = v
			return s
		},
		"github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion.ID",
	)
}

// MakeChatCompletionMessageToolCallUnionIDLensO returns a [__lens_option.LensO] for the ID field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion]
func MakeChatCompletionMessageToolCallUnionIDLensO() __lens_option.LensO[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string] {
	return __lens_option.FromIso[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion](__iso_option.FromZero[string]())(MakeChatCompletionMessageToolCallUnionIDLens())
}

// MakeChatCompletionMessageToolCallUnionIDRefLens returns a [__lens.Lens] for the ID field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion] via a pointer receiver
func MakeChatCompletionMessageToolCallUnionIDRefLens() __lens.Lens[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string] {
	return __lens.MakeLensStrictWithName(
		func(s *github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion) string { return s.ID },
		func(s *github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, v string) *github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion {
			s.ID = v
			return s
		},
		"(*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion).ID",
	)
}

// MakeChatCompletionMessageToolCallUnionIDRefLensO returns a [__lens_option.LensO] for the ID field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion] via a pointer receiver
func MakeChatCompletionMessageToolCallUnionIDRefLensO() __lens_option.LensO[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string] {
	return __lens_option.FromIso[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion](__iso_option.FromZero[string]())(MakeChatCompletionMessageToolCallUnionIDRefLens())
}

// MakeChatCompletionMessageToolCallUnionIDPrism returns a [__prism.Prism] for the ID field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion]
func MakeChatCompletionMessageToolCallUnionIDPrism() __prism.Prism[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion) __option.Option[string] {
			return _fromNonZero(s.ID)
		},
		func(v string) github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion {
			return github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion{ID: v}
		},
		"github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion.ID",
	)
}

// MakeChatCompletionMessageToolCallUnionIDRefPrism returns a [__prism.Prism] for the ID field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion] via a pointer receiver
func MakeChatCompletionMessageToolCallUnionIDRefPrism() __prism.Prism[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s *github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion) __option.Option[string] {
			return _fromNonZero(s.ID)
		},
		func(v string) *github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion {
			return &github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion{ID: v}
		},
		"github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion.ID",
	)
}

// MakeChatCompletionMessageToolCallUnionFunctionLens returns a [__lens.Lens] for the Function field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion]
func MakeChatCompletionMessageToolCallUnionFunctionLens() __lens.Lens[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction] {
	return __lens.MakeLensWithName(
		func(s github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion) github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction {
			return s.Function
		},
		func(s github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, v github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction) github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion {
			s.Function = v
			return s
		},
		"github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion.Function",
	)
}

// MakeChatCompletionMessageToolCallUnionFunctionRefLens returns a [__lens.Lens] for the Function field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion] via a pointer receiver
func MakeChatCompletionMessageToolCallUnionFunctionRefLens() __lens.Lens[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction] {
	return __lens.MakeLensRefWithName(
		func(s *github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion) github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction {
			return s.Function
		},
		func(s *github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, v github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction) *github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion {
			s.Function = v
			return s
		},
		"(*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion).Function",
	)
}

// MakeChatCompletionMessageToolCallUnionFunctionPrism returns a [__prism.Prism] for the Function field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion]
func MakeChatCompletionMessageToolCallUnionFunctionPrism() __prism.Prism[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction] {
	return __prism.MakePrismWithName(
		func(s github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion) __option.Option[github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction] {
			return __option.Some(s.Function)
		},
		func(v github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction) github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion {
			return github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion{Function: v}
		},
		"github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion.Function",
	)
}

// MakeChatCompletionMessageToolCallUnionFunctionRefPrism returns a [__prism.Prism] for the Function field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion] via a pointer receiver
func MakeChatCompletionMessageToolCallUnionFunctionRefPrism() __prism.Prism[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction] {
	return __prism.MakePrismWithName(
		func(s *github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion) __option.Option[github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction] {
			return __option.Some(s.Function)
		},
		func(v github_com_openai_openai_go_v3.ChatCompletionMessageFunctionToolCallFunction) *github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion {
			return &github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion{Function: v}
		},
		"github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion.Function",
	)
}

// MakeChatCompletionMessageToolCallUnionTypeLens returns a [__lens.Lens] for the Type field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion]
func MakeChatCompletionMessageToolCallUnionTypeLens() __lens.Lens[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string] {
	return __lens.MakeLensWithName(
		func(s github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion) string { return s.Type },
		func(s github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, v string) github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion {
			s.Type = v
			return s
		},
		"github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion.Type",
	)
}

// MakeChatCompletionMessageToolCallUnionTypeLensO returns a [__lens_option.LensO] for the Type field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion]
func MakeChatCompletionMessageToolCallUnionTypeLensO() __lens_option.LensO[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string] {
	return __lens_option.FromIso[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion](__iso_option.FromZero[string]())(MakeChatCompletionMessageToolCallUnionTypeLens())
}

// MakeChatCompletionMessageToolCallUnionTypeRefLens returns a [__lens.Lens] for the Type field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion] via a pointer receiver
func MakeChatCompletionMessageToolCallUnionTypeRefLens() __lens.Lens[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string] {
	return __lens.MakeLensStrictWithName(
		func(s *github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion) string { return s.Type },
		func(s *github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, v string) *github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion {
			s.Type = v
			return s
		},
		"(*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion).Type",
	)
}

// MakeChatCompletionMessageToolCallUnionTypeRefLensO returns a [__lens_option.LensO] for the Type field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion] via a pointer receiver
func MakeChatCompletionMessageToolCallUnionTypeRefLensO() __lens_option.LensO[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string] {
	return __lens_option.FromIso[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion](__iso_option.FromZero[string]())(MakeChatCompletionMessageToolCallUnionTypeRefLens())
}

// MakeChatCompletionMessageToolCallUnionTypePrism returns a [__prism.Prism] for the Type field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion]
func MakeChatCompletionMessageToolCallUnionTypePrism() __prism.Prism[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion) __option.Option[string] {
			return _fromNonZero(s.Type)
		},
		func(v string) github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion {
			return github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion{Type: v}
		},
		"github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion.Type",
	)
}

// MakeChatCompletionMessageToolCallUnionTypeRefPrism returns a [__prism.Prism] for the Type field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion] via a pointer receiver
func MakeChatCompletionMessageToolCallUnionTypeRefPrism() __prism.Prism[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s *github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion) __option.Option[string] {
			return _fromNonZero(s.Type)
		},
		func(v string) *github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion {
			return &github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion{Type: v}
		},
		"github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion.Type",
	)
}

// MakeChatCompletionMessageToolCallUnionCustomLens returns a [__lens.Lens] for the Custom field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion]
func MakeChatCompletionMessageToolCallUnionCustomLens() __lens.Lens[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, github_com_openai_openai_go_v3.ChatCompletionMessageCustomToolCallCustom] {
	return __lens.MakeLensWithName(
		func(s github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion) github_com_openai_openai_go_v3.ChatCompletionMessageCustomToolCallCustom {
			return s.Custom
		},
		func(s github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, v github_com_openai_openai_go_v3.ChatCompletionMessageCustomToolCallCustom) github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion {
			s.Custom = v
			return s
		},
		"github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion.Custom",
	)
}

// MakeChatCompletionMessageToolCallUnionCustomRefLens returns a [__lens.Lens] for the Custom field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion] via a pointer receiver
func MakeChatCompletionMessageToolCallUnionCustomRefLens() __lens.Lens[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, github_com_openai_openai_go_v3.ChatCompletionMessageCustomToolCallCustom] {
	return __lens.MakeLensRefWithName(
		func(s *github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion) github_com_openai_openai_go_v3.ChatCompletionMessageCustomToolCallCustom {
			return s.Custom
		},
		func(s *github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, v github_com_openai_openai_go_v3.ChatCompletionMessageCustomToolCallCustom) *github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion {
			s.Custom = v
			return s
		},
		"(*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion).Custom",
	)
}

// MakeChatCompletionMessageToolCallUnionCustomPrism returns a [__prism.Prism] for the Custom field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion]
func MakeChatCompletionMessageToolCallUnionCustomPrism() __prism.Prism[github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, github_com_openai_openai_go_v3.ChatCompletionMessageCustomToolCallCustom] {
	return __prism.MakePrismWithName(
		func(s github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion) __option.Option[github_com_openai_openai_go_v3.ChatCompletionMessageCustomToolCallCustom] {
			return __option.Some(s.Custom)
		},
		func(v github_com_openai_openai_go_v3.ChatCompletionMessageCustomToolCallCustom) github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion {
			return github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion{Custom: v}
		},
		"github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion.Custom",
	)
}

// MakeChatCompletionMessageToolCallUnionCustomRefPrism returns a [__prism.Prism] for the Custom field of [github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion] via a pointer receiver
func MakeChatCompletionMessageToolCallUnionCustomRefPrism() __prism.Prism[*github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion, github_com_openai_openai_go_v3.ChatCompletionMessageCustomToolCallCustom] {
	return __prism.MakePrismWithName(
		func(s *github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion) __option.Option[github_com_openai_openai_go_v3.ChatCompletionMessageCustomToolCallCustom] {
			return __option.Some(s.Custom)
		},
		func(v github_com_openai_openai_go_v3.ChatCompletionMessageCustomToolCallCustom) *github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion {
			return &github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion{Custom: v}
		},
		"github_com_openai_openai_go_v3.ChatCompletionMessageToolCallUnion.Custom",
	)
}

// MakeChatCompletionMessageToolCallUnionLenses creates a new [ChatCompletionMessageToolCallUnionLenses] with [lenses] for all fields
//
// [lenses]: __lens.Lens
func MakeChatCompletionMessageToolCallUnionLenses() ChatCompletionMessageToolCallUnionLenses {
	return ChatCompletionMessageToolCallUnionLenses{
		// mandatory lenses
		ID:       MakeChatCompletionMessageToolCallUnionIDLens(),
		Function: MakeChatCompletionMessageToolCallUnionFunctionLens(),
		Type:     MakeChatCompletionMessageToolCallUnionTypeLens(),
		Custom:   MakeChatCompletionMessageToolCallUnionCustomLens(),
		// optional lenses
		IDO:   MakeChatCompletionMessageToolCallUnionIDLensO(),
		TypeO: MakeChatCompletionMessageToolCallUnionTypeLensO(),
	}
}

// MakeChatCompletionMessageToolCallUnionRefLenses creates a new [ChatCompletionMessageToolCallUnionRefLenses] with [lenses] for all fields via a pointer to [ChatCompletionMessageToolCallUnion]
//
// [lenses]: __lens.Lens
func MakeChatCompletionMessageToolCallUnionRefLenses() ChatCompletionMessageToolCallUnionRefLenses {
	return ChatCompletionMessageToolCallUnionRefLenses{
		// mandatory lenses
		ID:       MakeChatCompletionMessageToolCallUnionIDRefLens(),
		Function: MakeChatCompletionMessageToolCallUnionFunctionRefLens(),
		Type:     MakeChatCompletionMessageToolCallUnionTypeRefLens(),
		Custom:   MakeChatCompletionMessageToolCallUnionCustomRefLens(),
		// optional lenses
		IDO:   MakeChatCompletionMessageToolCallUnionIDRefLensO(),
		TypeO: MakeChatCompletionMessageToolCallUnionTypeRefLensO(),
	}
}

// MakeChatCompletionMessageToolCallUnionPrisms creates a new [ChatCompletionMessageToolCallUnionPrisms] with [prisms] for all fields
//
// [prisms]: __prism.Prism
func MakeChatCompletionMessageToolCallUnionPrisms() ChatCompletionMessageToolCallUnionPrisms {
	return ChatCompletionMessageToolCallUnionPrisms{
		ID:       MakeChatCompletionMessageToolCallUnionIDPrism(),
		Function: MakeChatCompletionMessageToolCallUnionFunctionPrism(),
		Type:     MakeChatCompletionMessageToolCallUnionTypePrism(),
		Custom:   MakeChatCompletionMessageToolCallUnionCustomPrism(),
	}
}

// MakeChatCompletionMessageToolCallUnionRefPrisms creates a new [ChatCompletionMessageToolCallUnionRefPrisms] with [prisms] for all fields via a pointer to [ChatCompletionMessageToolCallUnion]
//
// [prisms]: __prism.Prism
func MakeChatCompletionMessageToolCallUnionRefPrisms() ChatCompletionMessageToolCallUnionRefPrisms {
	return ChatCompletionMessageToolCallUnionRefPrisms{
		ID:       MakeChatCompletionMessageToolCallUnionIDRefPrism(),
		Function: MakeChatCompletionMessageToolCallUnionFunctionRefPrism(),
		Type:     MakeChatCompletionMessageToolCallUnionTypeRefPrism(),
		Custom:   MakeChatCompletionMessageToolCallUnionCustomRefPrism(),
	}
}
