package tools

// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

import (
	__iso_option "github.com/IBM/fp-go/v2/optics/iso/option"
	__lens "github.com/IBM/fp-go/v2/optics/lens"
	__lens_option "github.com/IBM/fp-go/v2/optics/lens/option"
	__prism "github.com/IBM/fp-go/v2/optics/prism"
	__option "github.com/IBM/fp-go/v2/option"
	github_com_openai_openai_go_v3_packages_param "github.com/openai/openai-go/v3/packages/param"
	github_com_openai_openai_go_v3_shared "github.com/openai/openai-go/v3/shared"
)

// FunctionDefinitionParamLenses provides [lenses] for accessing fields of [FunctionDefinitionParam]
//
// [lenses]: __lens.Lens
type FunctionDefinitionParamLenses struct {
	// Name is a [__lens.Lens] for the Name field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam]
	Name __lens.Lens[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, string]
	// Strict is a [__lens.Lens] for the Strict field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam]
	Strict __lens.Lens[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[bool]]
	// Description is a [__lens.Lens] for the Description field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam]
	Description __lens.Lens[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[string]]
	// Parameters is a [__lens.Lens] for the Parameters field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam]
	Parameters __lens.Lens[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_shared.FunctionParameters]
	// NameO is a [__lens_option.LensO] for the Name field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam], treating the zero value as absent
	NameO __lens_option.LensO[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, string]
	// StrictO is a [__lens_option.LensO] for the Strict field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam], treating the zero value as absent
	StrictO __lens_option.LensO[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[bool]]
	// DescriptionO is a [__lens_option.LensO] for the Description field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam], treating the zero value as absent
	DescriptionO __lens_option.LensO[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[string]]
}

// FunctionDefinitionParamRefLenses provides [lenses] for accessing fields of [FunctionDefinitionParam] via a pointer to [FunctionDefinitionParam]
//
// [lenses]: __lens.Lens
type FunctionDefinitionParamRefLenses struct {
	// Name is a [__lens.Lens] for the Name field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver
	Name __lens.Lens[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, string]
	// Strict is a [__lens.Lens] for the Strict field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver
	Strict __lens.Lens[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[bool]]
	// Description is a [__lens.Lens] for the Description field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver
	Description __lens.Lens[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[string]]
	// Parameters is a [__lens.Lens] for the Parameters field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver
	Parameters __lens.Lens[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_shared.FunctionParameters]
	// NameO is a [__lens_option.LensO] for the Name field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver, treating the zero value as absent
	NameO __lens_option.LensO[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, string]
	// StrictO is a [__lens_option.LensO] for the Strict field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver, treating the zero value as absent
	StrictO __lens_option.LensO[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[bool]]
	// DescriptionO is a [__lens_option.LensO] for the Description field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver, treating the zero value as absent
	DescriptionO __lens_option.LensO[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[string]]
}

// FunctionDefinitionParamPrisms provides [prisms] for accessing fields of [FunctionDefinitionParam]
//
// [prisms]: __prism.Prism
type FunctionDefinitionParamPrisms struct {
	// Name is a [__prism.Prism] for the Name field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam]
	Name __prism.Prism[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, string]
	// Strict is a [__prism.Prism] for the Strict field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam]
	Strict __prism.Prism[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[bool]]
	// Description is a [__prism.Prism] for the Description field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam]
	Description __prism.Prism[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[string]]
	// Parameters is a [__prism.Prism] for the Parameters field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam]
	Parameters __prism.Prism[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_shared.FunctionParameters]
}

// FunctionDefinitionParamRefPrisms provides [prisms] for accessing fields of [FunctionDefinitionParam] via a pointer to [FunctionDefinitionParam]
//
// [prisms]: __prism.Prism
type FunctionDefinitionParamRefPrisms struct {
	// Name is a [__prism.Prism] for the Name field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver
	Name __prism.Prism[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, string]
	// Strict is a [__prism.Prism] for the Strict field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver
	Strict __prism.Prism[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[bool]]
	// Description is a [__prism.Prism] for the Description field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver
	Description __prism.Prism[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[string]]
	// Parameters is a [__prism.Prism] for the Parameters field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver
	Parameters __prism.Prism[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_shared.FunctionParameters]
}

// MakeFunctionDefinitionParamNameLens returns a [__lens.Lens] for the Name field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam]
func MakeFunctionDefinitionParamNameLens() __lens.Lens[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, string] {
	return __lens.MakeLensWithName(
		func(s github_com_openai_openai_go_v3_shared.FunctionDefinitionParam) string { return s.Name },
		func(s github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, v string) github_com_openai_openai_go_v3_shared.FunctionDefinitionParam {
			s.Name = v
			return s
		},
		"github_com_openai_openai_go_v3_shared.FunctionDefinitionParam.Name",
	)
}

// MakeFunctionDefinitionParamNameLensO returns a [__lens_option.LensO] for the Name field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam]
func MakeFunctionDefinitionParamNameLensO() __lens_option.LensO[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, string] {
	return __lens_option.FromIso[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam](__iso_option.FromZero[string]())(MakeFunctionDefinitionParamNameLens())
}

// MakeFunctionDefinitionParamNameRefLens returns a [__lens.Lens] for the Name field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver
func MakeFunctionDefinitionParamNameRefLens() __lens.Lens[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, string] {
	return __lens.MakeLensStrictWithName(
		func(s *github_com_openai_openai_go_v3_shared.FunctionDefinitionParam) string { return s.Name },
		func(s *github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, v string) *github_com_openai_openai_go_v3_shared.FunctionDefinitionParam {
			s.Name = v
			return s
		},
		"(*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam).Name",
	)
}

// MakeFunctionDefinitionParamNameRefLensO returns a [__lens_option.LensO] for the Name field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver
func MakeFunctionDefinitionParamNameRefLensO() __lens_option.LensO[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, string] {
	return __lens_option.FromIso[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam](__iso_option.FromZero[string]())(MakeFunctionDefinitionParamNameRefLens())
}

// MakeFunctionDefinitionParamNamePrism returns a [__prism.Prism] for the Name field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam]
func MakeFunctionDefinitionParamNamePrism() __prism.Prism[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s github_com_openai_openai_go_v3_shared.FunctionDefinitionParam) __option.Option[string] {
			return _fromNonZero(s.Name)
		},
		func(v string) github_com_openai_openai_go_v3_shared.FunctionDefinitionParam {
			return github_com_openai_openai_go_v3_shared.FunctionDefinitionParam{Name: v}
		},
		"github_com_openai_openai_go_v3_shared.FunctionDefinitionParam.Name",
	)
}

// MakeFunctionDefinitionParamNameRefPrism returns a [__prism.Prism] for the Name field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver
func MakeFunctionDefinitionParamNameRefPrism() __prism.Prism[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s *github_com_openai_openai_go_v3_shared.FunctionDefinitionParam) __option.Option[string] {
			return _fromNonZero(s.Name)
		},
		func(v string) *github_com_openai_openai_go_v3_shared.FunctionDefinitionParam {
			return &github_com_openai_openai_go_v3_shared.FunctionDefinitionParam{Name: v}
		},
		"github_com_openai_openai_go_v3_shared.FunctionDefinitionParam.Name",
	)
}

// MakeFunctionDefinitionParamStrictLens returns a [__lens.Lens] for the Strict field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam]
func MakeFunctionDefinitionParamStrictLens() __lens.Lens[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[bool]] {
	return __lens.MakeLensWithName(
		func(s github_com_openai_openai_go_v3_shared.FunctionDefinitionParam) github_com_openai_openai_go_v3_packages_param.Opt[bool] {
			return s.Strict
		},
		func(s github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, v github_com_openai_openai_go_v3_packages_param.Opt[bool]) github_com_openai_openai_go_v3_shared.FunctionDefinitionParam {
			s.Strict = v
			return s
		},
		"github_com_openai_openai_go_v3_shared.FunctionDefinitionParam.Strict",
	)
}

// MakeFunctionDefinitionParamStrictLensO returns a [__lens_option.LensO] for the Strict field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam]
func MakeFunctionDefinitionParamStrictLensO() __lens_option.LensO[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[bool]] {
	return __lens_option.FromIso[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam](__iso_option.FromZero[github_com_openai_openai_go_v3_packages_param.Opt[bool]]())(MakeFunctionDefinitionParamStrictLens())
}

// MakeFunctionDefinitionParamStrictRefLens returns a [__lens.Lens] for the Strict field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver
func MakeFunctionDefinitionParamStrictRefLens() __lens.Lens[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[bool]] {
	return __lens.MakeLensStrictWithName(
		func(s *github_com_openai_openai_go_v3_shared.FunctionDefinitionParam) github_com_openai_openai_go_v3_packages_param.Opt[bool] {
			return s.Strict
		},
		func(s *github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, v github_com_openai_openai_go_v3_packages_param.Opt[bool]) *github_com_openai_openai_go_v3_shared.FunctionDefinitionParam {
			s.Strict = v
			return s
		},
		"(*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam).Strict",
	)
}

// MakeFunctionDefinitionParamStrictRefLensO returns a [__lens_option.LensO] for the Strict field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver
func MakeFunctionDefinitionParamStrictRefLensO() __lens_option.LensO[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[bool]] {
	return __lens_option.FromIso[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam](__iso_option.FromZero[github_com_openai_openai_go_v3_packages_param.Opt[bool]]())(MakeFunctionDefinitionParamStrictRefLens())
}

// MakeFunctionDefinitionParamStrictPrism returns a [__prism.Prism] for the Strict field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam]
func MakeFunctionDefinitionParamStrictPrism() __prism.Prism[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[bool]] {
	_fromNonZero := __option.FromNonZero[github_com_openai_openai_go_v3_packages_param.Opt[bool]]()
	return __prism.MakePrismWithName(
		func(s github_com_openai_openai_go_v3_shared.FunctionDefinitionParam) __option.Option[github_com_openai_openai_go_v3_packages_param.Opt[bool]] {
			return _fromNonZero(s.Strict)
		},
		func(v github_com_openai_openai_go_v3_packages_param.Opt[bool]) github_com_openai_openai_go_v3_shared.FunctionDefinitionParam {
			return github_com_openai_openai_go_v3_shared.FunctionDefinitionParam{Strict: v}
		},
		"github_com_openai_openai_go_v3_shared.FunctionDefinitionParam.Strict",
	)
}

// MakeFunctionDefinitionParamStrictRefPrism returns a [__prism.Prism] for the Strict field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver
func MakeFunctionDefinitionParamStrictRefPrism() __prism.Prism[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[bool]] {
	_fromNonZero := __option.FromNonZero[github_com_openai_openai_go_v3_packages_param.Opt[bool]]()
	return __prism.MakePrismWithName(
		func(s *github_com_openai_openai_go_v3_shared.FunctionDefinitionParam) __option.Option[github_com_openai_openai_go_v3_packages_param.Opt[bool]] {
			return _fromNonZero(s.Strict)
		},
		func(v github_com_openai_openai_go_v3_packages_param.Opt[bool]) *github_com_openai_openai_go_v3_shared.FunctionDefinitionParam {
			return &github_com_openai_openai_go_v3_shared.FunctionDefinitionParam{Strict: v}
		},
		"github_com_openai_openai_go_v3_shared.FunctionDefinitionParam.Strict",
	)
}

// MakeFunctionDefinitionParamDescriptionLens returns a [__lens.Lens] for the Description field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam]
func MakeFunctionDefinitionParamDescriptionLens() __lens.Lens[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[string]] {
	return __lens.MakeLensWithName(
		func(s github_com_openai_openai_go_v3_shared.FunctionDefinitionParam) github_com_openai_openai_go_v3_packages_param.Opt[string] {
			return s.Description
		},
		func(s github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, v github_com_openai_openai_go_v3_packages_param.Opt[string]) github_com_openai_openai_go_v3_shared.FunctionDefinitionParam {
			s.Description = v
			return s
		},
		"github_com_openai_openai_go_v3_shared.FunctionDefinitionParam.Description",
	)
}

// MakeFunctionDefinitionParamDescriptionLensO returns a [__lens_option.LensO] for the Description field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam]
func MakeFunctionDefinitionParamDescriptionLensO() __lens_option.LensO[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[string]] {
	return __lens_option.FromIso[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam](__iso_option.FromZero[github_com_openai_openai_go_v3_packages_param.Opt[string]]())(MakeFunctionDefinitionParamDescriptionLens())
}

// MakeFunctionDefinitionParamDescriptionRefLens returns a [__lens.Lens] for the Description field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver
func MakeFunctionDefinitionParamDescriptionRefLens() __lens.Lens[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[string]] {
	return __lens.MakeLensStrictWithName(
		func(s *github_com_openai_openai_go_v3_shared.FunctionDefinitionParam) github_com_openai_openai_go_v3_packages_param.Opt[string] {
			return s.Description
		},
		func(s *github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, v github_com_openai_openai_go_v3_packages_param.Opt[string]) *github_com_openai_openai_go_v3_shared.FunctionDefinitionParam {
			s.Description = v
			return s
		},
		"(*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam).Description",
	)
}

// MakeFunctionDefinitionParamDescriptionRefLensO returns a [__lens_option.LensO] for the Description field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver
func MakeFunctionDefinitionParamDescriptionRefLensO() __lens_option.LensO[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[string]] {
	return __lens_option.FromIso[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam](__iso_option.FromZero[github_com_openai_openai_go_v3_packages_param.Opt[string]]())(MakeFunctionDefinitionParamDescriptionRefLens())
}

// MakeFunctionDefinitionParamDescriptionPrism returns a [__prism.Prism] for the Description field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam]
func MakeFunctionDefinitionParamDescriptionPrism() __prism.Prism[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[string]] {
	_fromNonZero := __option.FromNonZero[github_com_openai_openai_go_v3_packages_param.Opt[string]]()
	return __prism.MakePrismWithName(
		func(s github_com_openai_openai_go_v3_shared.FunctionDefinitionParam) __option.Option[github_com_openai_openai_go_v3_packages_param.Opt[string]] {
			return _fromNonZero(s.Description)
		},
		func(v github_com_openai_openai_go_v3_packages_param.Opt[string]) github_com_openai_openai_go_v3_shared.FunctionDefinitionParam {
			return github_com_openai_openai_go_v3_shared.FunctionDefinitionParam{Description: v}
		},
		"github_com_openai_openai_go_v3_shared.FunctionDefinitionParam.Description",
	)
}

// MakeFunctionDefinitionParamDescriptionRefPrism returns a [__prism.Prism] for the Description field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver
func MakeFunctionDefinitionParamDescriptionRefPrism() __prism.Prism[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_packages_param.Opt[string]] {
	_fromNonZero := __option.FromNonZero[github_com_openai_openai_go_v3_packages_param.Opt[string]]()
	return __prism.MakePrismWithName(
		func(s *github_com_openai_openai_go_v3_shared.FunctionDefinitionParam) __option.Option[github_com_openai_openai_go_v3_packages_param.Opt[string]] {
			return _fromNonZero(s.Description)
		},
		func(v github_com_openai_openai_go_v3_packages_param.Opt[string]) *github_com_openai_openai_go_v3_shared.FunctionDefinitionParam {
			return &github_com_openai_openai_go_v3_shared.FunctionDefinitionParam{Description: v}
		},
		"github_com_openai_openai_go_v3_shared.FunctionDefinitionParam.Description",
	)
}

// MakeFunctionDefinitionParamParametersLens returns a [__lens.Lens] for the Parameters field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam]
func MakeFunctionDefinitionParamParametersLens() __lens.Lens[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_shared.FunctionParameters] {
	return __lens.MakeLensWithName(
		func(s github_com_openai_openai_go_v3_shared.FunctionDefinitionParam) github_com_openai_openai_go_v3_shared.FunctionParameters {
			return s.Parameters
		},
		func(s github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, v github_com_openai_openai_go_v3_shared.FunctionParameters) github_com_openai_openai_go_v3_shared.FunctionDefinitionParam {
			s.Parameters = v
			return s
		},
		"github_com_openai_openai_go_v3_shared.FunctionDefinitionParam.Parameters",
	)
}

// MakeFunctionDefinitionParamParametersRefLens returns a [__lens.Lens] for the Parameters field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver
func MakeFunctionDefinitionParamParametersRefLens() __lens.Lens[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_shared.FunctionParameters] {
	return __lens.MakeLensRefWithName(
		func(s *github_com_openai_openai_go_v3_shared.FunctionDefinitionParam) github_com_openai_openai_go_v3_shared.FunctionParameters {
			return s.Parameters
		},
		func(s *github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, v github_com_openai_openai_go_v3_shared.FunctionParameters) *github_com_openai_openai_go_v3_shared.FunctionDefinitionParam {
			s.Parameters = v
			return s
		},
		"(*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam).Parameters",
	)
}

// MakeFunctionDefinitionParamParametersPrism returns a [__prism.Prism] for the Parameters field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam]
func MakeFunctionDefinitionParamParametersPrism() __prism.Prism[github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_shared.FunctionParameters] {
	return __prism.MakePrismWithName(
		func(s github_com_openai_openai_go_v3_shared.FunctionDefinitionParam) __option.Option[github_com_openai_openai_go_v3_shared.FunctionParameters] {
			return __option.Some(s.Parameters)
		},
		func(v github_com_openai_openai_go_v3_shared.FunctionParameters) github_com_openai_openai_go_v3_shared.FunctionDefinitionParam {
			return github_com_openai_openai_go_v3_shared.FunctionDefinitionParam{Parameters: v}
		},
		"github_com_openai_openai_go_v3_shared.FunctionDefinitionParam.Parameters",
	)
}

// MakeFunctionDefinitionParamParametersRefPrism returns a [__prism.Prism] for the Parameters field of [github_com_openai_openai_go_v3_shared.FunctionDefinitionParam] via a pointer receiver
func MakeFunctionDefinitionParamParametersRefPrism() __prism.Prism[*github_com_openai_openai_go_v3_shared.FunctionDefinitionParam, github_com_openai_openai_go_v3_shared.FunctionParameters] {
	return __prism.MakePrismWithName(
		func(s *github_com_openai_openai_go_v3_shared.FunctionDefinitionParam) __option.Option[github_com_openai_openai_go_v3_shared.FunctionParameters] {
			return __option.Some(s.Parameters)
		},
		func(v github_com_openai_openai_go_v3_shared.FunctionParameters) *github_com_openai_openai_go_v3_shared.FunctionDefinitionParam {
			return &github_com_openai_openai_go_v3_shared.FunctionDefinitionParam{Parameters: v}
		},
		"github_com_openai_openai_go_v3_shared.FunctionDefinitionParam.Parameters",
	)
}

// MakeFunctionDefinitionParamLenses creates a new [FunctionDefinitionParamLenses] with [lenses] for all fields
//
// [lenses]: __lens.Lens
func MakeFunctionDefinitionParamLenses() FunctionDefinitionParamLenses {
	return FunctionDefinitionParamLenses{
		// mandatory lenses
		Name:        MakeFunctionDefinitionParamNameLens(),
		Strict:      MakeFunctionDefinitionParamStrictLens(),
		Description: MakeFunctionDefinitionParamDescriptionLens(),
		Parameters:  MakeFunctionDefinitionParamParametersLens(),
		// optional lenses
		NameO:        MakeFunctionDefinitionParamNameLensO(),
		StrictO:      MakeFunctionDefinitionParamStrictLensO(),
		DescriptionO: MakeFunctionDefinitionParamDescriptionLensO(),
	}
}

// MakeFunctionDefinitionParamRefLenses creates a new [FunctionDefinitionParamRefLenses] with [lenses] for all fields via a pointer to [FunctionDefinitionParam]
//
// [lenses]: __lens.Lens
func MakeFunctionDefinitionParamRefLenses() FunctionDefinitionParamRefLenses {
	return FunctionDefinitionParamRefLenses{
		// mandatory lenses
		Name:        MakeFunctionDefinitionParamNameRefLens(),
		Strict:      MakeFunctionDefinitionParamStrictRefLens(),
		Description: MakeFunctionDefinitionParamDescriptionRefLens(),
		Parameters:  MakeFunctionDefinitionParamParametersRefLens(),
		// optional lenses
		NameO:        MakeFunctionDefinitionParamNameRefLensO(),
		StrictO:      MakeFunctionDefinitionParamStrictRefLensO(),
		DescriptionO: MakeFunctionDefinitionParamDescriptionRefLensO(),
	}
}

// MakeFunctionDefinitionParamPrisms creates a new [FunctionDefinitionParamPrisms] with [prisms] for all fields
//
// [prisms]: __prism.Prism
func MakeFunctionDefinitionParamPrisms() FunctionDefinitionParamPrisms {
	return FunctionDefinitionParamPrisms{
		Name:        MakeFunctionDefinitionParamNamePrism(),
		Strict:      MakeFunctionDefinitionParamStrictPrism(),
		Description: MakeFunctionDefinitionParamDescriptionPrism(),
		Parameters:  MakeFunctionDefinitionParamParametersPrism(),
	}
}

// MakeFunctionDefinitionParamRefPrisms creates a new [FunctionDefinitionParamRefPrisms] with [prisms] for all fields via a pointer to [FunctionDefinitionParam]
//
// [prisms]: __prism.Prism
func MakeFunctionDefinitionParamRefPrisms() FunctionDefinitionParamRefPrisms {
	return FunctionDefinitionParamRefPrisms{
		Name:        MakeFunctionDefinitionParamNameRefPrism(),
		Strict:      MakeFunctionDefinitionParamStrictRefPrism(),
		Description: MakeFunctionDefinitionParamDescriptionRefPrism(),
		Parameters:  MakeFunctionDefinitionParamParametersRefPrism(),
	}
}
