package tools

// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

import (
	__iso_option "github.com/IBM/fp-go/v2/optics/iso/option"
	__lens "github.com/IBM/fp-go/v2/optics/lens"
	__lens_option "github.com/IBM/fp-go/v2/optics/lens/option"
	__prism "github.com/IBM/fp-go/v2/optics/prism"
	__option "github.com/IBM/fp-go/v2/option"
)

// ReadFileArgsLenses provides [lenses] for accessing fields of [ReadFileArgs]
//
// [lenses]: __lens.Lens
type ReadFileArgsLenses struct {
	// Path is a [__lens.Lens] for the Path field of [ReadFileArgs]
	Path __lens.Lens[ReadFileArgs, string]
	// Range is a [__lens.Lens] for the Range field of [ReadFileArgs]
	Range __lens.Lens[ReadFileArgs, string]
	// Name is a [__lens.Lens] for the Name field of [ReadFileArgs]
	Name __lens.Lens[ReadFileArgs, string]
	// Content is a [__lens.Lens] for the Content field of [ReadFileArgs]
	Content __lens.Lens[ReadFileArgs, []byte]
	// PathO is a [__lens_option.LensO] for the Path field of [ReadFileArgs], treating the zero value as absent
	PathO __lens_option.LensO[ReadFileArgs, string]
	// RangeO is a [__lens_option.LensO] for the Range field of [ReadFileArgs], treating the zero value as absent
	RangeO __lens_option.LensO[ReadFileArgs, string]
	// NameO is a [__lens_option.LensO] for the Name field of [ReadFileArgs], treating the zero value as absent
	NameO __lens_option.LensO[ReadFileArgs, string]
}

// ReadFileArgsRefLenses provides [lenses] for accessing fields of [ReadFileArgs] via a pointer to [ReadFileArgs]
//
// [lenses]: __lens.Lens
type ReadFileArgsRefLenses struct {
	// Path is a [__lens.Lens] for the Path field of [ReadFileArgs] via a pointer receiver
	Path __lens.Lens[*ReadFileArgs, string]
	// Range is a [__lens.Lens] for the Range field of [ReadFileArgs] via a pointer receiver
	Range __lens.Lens[*ReadFileArgs, string]
	// Name is a [__lens.Lens] for the Name field of [ReadFileArgs] via a pointer receiver
	Name __lens.Lens[*ReadFileArgs, string]
	// Content is a [__lens.Lens] for the Content field of [ReadFileArgs] via a pointer receiver
	Content __lens.Lens[*ReadFileArgs, []byte]
	// PathO is a [__lens_option.LensO] for the Path field of [ReadFileArgs] via a pointer receiver, treating the zero value as absent
	PathO __lens_option.LensO[*ReadFileArgs, string]
	// RangeO is a [__lens_option.LensO] for the Range field of [ReadFileArgs] via a pointer receiver, treating the zero value as absent
	RangeO __lens_option.LensO[*ReadFileArgs, string]
	// NameO is a [__lens_option.LensO] for the Name field of [ReadFileArgs] via a pointer receiver, treating the zero value as absent
	NameO __lens_option.LensO[*ReadFileArgs, string]
}

// ReadFileArgsPrisms provides [prisms] for accessing fields of [ReadFileArgs]
//
// [prisms]: __prism.Prism
type ReadFileArgsPrisms struct {
	// Path is a [__prism.Prism] for the Path field of [ReadFileArgs]
	Path __prism.Prism[ReadFileArgs, string]
	// Range is a [__prism.Prism] for the Range field of [ReadFileArgs]
	Range __prism.Prism[ReadFileArgs, string]
	// Name is a [__prism.Prism] for the Name field of [ReadFileArgs]
	Name __prism.Prism[ReadFileArgs, string]
	// Content is a [__prism.Prism] for the Content field of [ReadFileArgs]
	Content __prism.Prism[ReadFileArgs, []byte]
}

// ReadFileArgsRefPrisms provides [prisms] for accessing fields of [ReadFileArgs] via a pointer to [ReadFileArgs]
//
// [prisms]: __prism.Prism
type ReadFileArgsRefPrisms struct {
	// Path is a [__prism.Prism] for the Path field of [ReadFileArgs] via a pointer receiver
	Path __prism.Prism[*ReadFileArgs, string]
	// Range is a [__prism.Prism] for the Range field of [ReadFileArgs] via a pointer receiver
	Range __prism.Prism[*ReadFileArgs, string]
	// Name is a [__prism.Prism] for the Name field of [ReadFileArgs] via a pointer receiver
	Name __prism.Prism[*ReadFileArgs, string]
	// Content is a [__prism.Prism] for the Content field of [ReadFileArgs] via a pointer receiver
	Content __prism.Prism[*ReadFileArgs, []byte]
}

// MakeReadFileArgsPathLens returns a [__lens.Lens] for the Path field of [ReadFileArgs]
func MakeReadFileArgsPathLens() __lens.Lens[ReadFileArgs, string] {
	return __lens.MakeLensWithName(
		func(s ReadFileArgs) string { return s.Path },
		func(s ReadFileArgs, v string) ReadFileArgs { s.Path = v; return s },
		"ReadFileArgs.Path",
	)
}

// MakeReadFileArgsPathLensO returns a [__lens_option.LensO] for the Path field of [ReadFileArgs]
func MakeReadFileArgsPathLensO() __lens_option.LensO[ReadFileArgs, string] {
	return __lens_option.FromIso[ReadFileArgs](__iso_option.FromZero[string]())(MakeReadFileArgsPathLens())
}

// MakeReadFileArgsPathRefLens returns a [__lens.Lens] for the Path field of [ReadFileArgs] via a pointer receiver
func MakeReadFileArgsPathRefLens() __lens.Lens[*ReadFileArgs, string] {
	return __lens.MakeLensStrictWithName(
		func(s *ReadFileArgs) string { return s.Path },
		func(s *ReadFileArgs, v string) *ReadFileArgs { s.Path = v; return s },
		"(*ReadFileArgs).Path",
	)
}

// MakeReadFileArgsPathRefLensO returns a [__lens_option.LensO] for the Path field of [ReadFileArgs] via a pointer receiver
func MakeReadFileArgsPathRefLensO() __lens_option.LensO[*ReadFileArgs, string] {
	return __lens_option.FromIso[*ReadFileArgs](__iso_option.FromZero[string]())(MakeReadFileArgsPathRefLens())
}

// MakeReadFileArgsPathPrism returns a [__prism.Prism] for the Path field of [ReadFileArgs]
func MakeReadFileArgsPathPrism() __prism.Prism[ReadFileArgs, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s ReadFileArgs) __option.Option[string] { return _fromNonZero(s.Path) },
		func(v string) ReadFileArgs {
			return ReadFileArgs{Path: v}
		},
		"ReadFileArgs.Path",
	)
}

// MakeReadFileArgsPathRefPrism returns a [__prism.Prism] for the Path field of [ReadFileArgs] via a pointer receiver
func MakeReadFileArgsPathRefPrism() __prism.Prism[*ReadFileArgs, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s *ReadFileArgs) __option.Option[string] { return _fromNonZero(s.Path) },
		func(v string) *ReadFileArgs {
			return &ReadFileArgs{Path: v}
		},
		"ReadFileArgs.Path",
	)
}

// MakeReadFileArgsRangeLens returns a [__lens.Lens] for the Range field of [ReadFileArgs]
func MakeReadFileArgsRangeLens() __lens.Lens[ReadFileArgs, string] {
	return __lens.MakeLensWithName(
		func(s ReadFileArgs) string { return s.Range },
		func(s ReadFileArgs, v string) ReadFileArgs { s.Range = v; return s },
		"ReadFileArgs.Range",
	)
}

// MakeReadFileArgsRangeLensO returns a [__lens_option.LensO] for the Range field of [ReadFileArgs]
func MakeReadFileArgsRangeLensO() __lens_option.LensO[ReadFileArgs, string] {
	return __lens_option.FromIso[ReadFileArgs](__iso_option.FromZero[string]())(MakeReadFileArgsRangeLens())
}

// MakeReadFileArgsRangeRefLens returns a [__lens.Lens] for the Range field of [ReadFileArgs] via a pointer receiver
func MakeReadFileArgsRangeRefLens() __lens.Lens[*ReadFileArgs, string] {
	return __lens.MakeLensStrictWithName(
		func(s *ReadFileArgs) string { return s.Range },
		func(s *ReadFileArgs, v string) *ReadFileArgs { s.Range = v; return s },
		"(*ReadFileArgs).Range",
	)
}

// MakeReadFileArgsRangeRefLensO returns a [__lens_option.LensO] for the Range field of [ReadFileArgs] via a pointer receiver
func MakeReadFileArgsRangeRefLensO() __lens_option.LensO[*ReadFileArgs, string] {
	return __lens_option.FromIso[*ReadFileArgs](__iso_option.FromZero[string]())(MakeReadFileArgsRangeRefLens())
}

// MakeReadFileArgsRangePrism returns a [__prism.Prism] for the Range field of [ReadFileArgs]
func MakeReadFileArgsRangePrism() __prism.Prism[ReadFileArgs, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s ReadFileArgs) __option.Option[string] { return _fromNonZero(s.Range) },
		func(v string) ReadFileArgs {
			return ReadFileArgs{Range: v}
		},
		"ReadFileArgs.Range",
	)
}

// MakeReadFileArgsRangeRefPrism returns a [__prism.Prism] for the Range field of [ReadFileArgs] via a pointer receiver
func MakeReadFileArgsRangeRefPrism() __prism.Prism[*ReadFileArgs, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s *ReadFileArgs) __option.Option[string] { return _fromNonZero(s.Range) },
		func(v string) *ReadFileArgs {
			return &ReadFileArgs{Range: v}
		},
		"ReadFileArgs.Range",
	)
}

// MakeReadFileArgsNameLens returns a [__lens.Lens] for the Name field of [ReadFileArgs]
func MakeReadFileArgsNameLens() __lens.Lens[ReadFileArgs, string] {
	return __lens.MakeLensWithName(
		func(s ReadFileArgs) string { return s.Name },
		func(s ReadFileArgs, v string) ReadFileArgs { s.Name = v; return s },
		"ReadFileArgs.Name",
	)
}

// MakeReadFileArgsNameLensO returns a [__lens_option.LensO] for the Name field of [ReadFileArgs]
func MakeReadFileArgsNameLensO() __lens_option.LensO[ReadFileArgs, string] {
	return __lens_option.FromIso[ReadFileArgs](__iso_option.FromZero[string]())(MakeReadFileArgsNameLens())
}

// MakeReadFileArgsNameRefLens returns a [__lens.Lens] for the Name field of [ReadFileArgs] via a pointer receiver
func MakeReadFileArgsNameRefLens() __lens.Lens[*ReadFileArgs, string] {
	return __lens.MakeLensStrictWithName(
		func(s *ReadFileArgs) string { return s.Name },
		func(s *ReadFileArgs, v string) *ReadFileArgs { s.Name = v; return s },
		"(*ReadFileArgs).Name",
	)
}

// MakeReadFileArgsNameRefLensO returns a [__lens_option.LensO] for the Name field of [ReadFileArgs] via a pointer receiver
func MakeReadFileArgsNameRefLensO() __lens_option.LensO[*ReadFileArgs, string] {
	return __lens_option.FromIso[*ReadFileArgs](__iso_option.FromZero[string]())(MakeReadFileArgsNameRefLens())
}

// MakeReadFileArgsNamePrism returns a [__prism.Prism] for the Name field of [ReadFileArgs]
func MakeReadFileArgsNamePrism() __prism.Prism[ReadFileArgs, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s ReadFileArgs) __option.Option[string] { return _fromNonZero(s.Name) },
		func(v string) ReadFileArgs {
			return ReadFileArgs{Name: v}
		},
		"ReadFileArgs.Name",
	)
}

// MakeReadFileArgsNameRefPrism returns a [__prism.Prism] for the Name field of [ReadFileArgs] via a pointer receiver
func MakeReadFileArgsNameRefPrism() __prism.Prism[*ReadFileArgs, string] {
	_fromNonZero := __option.FromNonZero[string]()
	return __prism.MakePrismWithName(
		func(s *ReadFileArgs) __option.Option[string] { return _fromNonZero(s.Name) },
		func(v string) *ReadFileArgs {
			return &ReadFileArgs{Name: v}
		},
		"ReadFileArgs.Name",
	)
}

// MakeReadFileArgsContentLens returns a [__lens.Lens] for the Content field of [ReadFileArgs]
func MakeReadFileArgsContentLens() __lens.Lens[ReadFileArgs, []byte] {
	return __lens.MakeLensWithName(
		func(s ReadFileArgs) []byte { return s.Content },
		func(s ReadFileArgs, v []byte) ReadFileArgs { s.Content = v; return s },
		"ReadFileArgs.Content",
	)
}

// MakeReadFileArgsContentRefLens returns a [__lens.Lens] for the Content field of [ReadFileArgs] via a pointer receiver
func MakeReadFileArgsContentRefLens() __lens.Lens[*ReadFileArgs, []byte] {
	return __lens.MakeLensRefWithName(
		func(s *ReadFileArgs) []byte { return s.Content },
		func(s *ReadFileArgs, v []byte) *ReadFileArgs { s.Content = v; return s },
		"(*ReadFileArgs).Content",
	)
}

// MakeReadFileArgsContentPrism returns a [__prism.Prism] for the Content field of [ReadFileArgs]
func MakeReadFileArgsContentPrism() __prism.Prism[ReadFileArgs, []byte] {
	return __prism.MakePrismWithName(
		func(s ReadFileArgs) __option.Option[[]byte] { return __option.Some(s.Content) },
		func(v []byte) ReadFileArgs {
			return ReadFileArgs{Content: v}
		},
		"ReadFileArgs.Content",
	)
}

// MakeReadFileArgsContentRefPrism returns a [__prism.Prism] for the Content field of [ReadFileArgs] via a pointer receiver
func MakeReadFileArgsContentRefPrism() __prism.Prism[*ReadFileArgs, []byte] {
	return __prism.MakePrismWithName(
		func(s *ReadFileArgs) __option.Option[[]byte] { return __option.Some(s.Content) },
		func(v []byte) *ReadFileArgs {
			return &ReadFileArgs{Content: v}
		},
		"ReadFileArgs.Content",
	)
}

// MakeReadFileArgsLenses creates a new [ReadFileArgsLenses] with [lenses] for all fields
//
// [lenses]: __lens.Lens
func MakeReadFileArgsLenses() ReadFileArgsLenses {
	return ReadFileArgsLenses{
		// mandatory lenses
		Path:    MakeReadFileArgsPathLens(),
		Range:   MakeReadFileArgsRangeLens(),
		Name:    MakeReadFileArgsNameLens(),
		Content: MakeReadFileArgsContentLens(),
		// optional lenses
		PathO:  MakeReadFileArgsPathLensO(),
		RangeO: MakeReadFileArgsRangeLensO(),
		NameO:  MakeReadFileArgsNameLensO(),
	}
}

// MakeReadFileArgsRefLenses creates a new [ReadFileArgsRefLenses] with [lenses] for all fields via a pointer to [ReadFileArgs]
//
// [lenses]: __lens.Lens
func MakeReadFileArgsRefLenses() ReadFileArgsRefLenses {
	return ReadFileArgsRefLenses{
		// mandatory lenses
		Path:    MakeReadFileArgsPathRefLens(),
		Range:   MakeReadFileArgsRangeRefLens(),
		Name:    MakeReadFileArgsNameRefLens(),
		Content: MakeReadFileArgsContentRefLens(),
		// optional lenses
		PathO:  MakeReadFileArgsPathRefLensO(),
		RangeO: MakeReadFileArgsRangeRefLensO(),
		NameO:  MakeReadFileArgsNameRefLensO(),
	}
}

// MakeReadFileArgsPrisms creates a new [ReadFileArgsPrisms] with [prisms] for all fields
//
// [prisms]: __prism.Prism
func MakeReadFileArgsPrisms() ReadFileArgsPrisms {
	return ReadFileArgsPrisms{
		Path:    MakeReadFileArgsPathPrism(),
		Range:   MakeReadFileArgsRangePrism(),
		Name:    MakeReadFileArgsNamePrism(),
		Content: MakeReadFileArgsContentPrism(),
	}
}

// MakeReadFileArgsRefPrisms creates a new [ReadFileArgsRefPrisms] with [prisms] for all fields via a pointer to [ReadFileArgs]
//
// [prisms]: __prism.Prism
func MakeReadFileArgsRefPrisms() ReadFileArgsRefPrisms {
	return ReadFileArgsRefPrisms{
		Path:    MakeReadFileArgsPathRefPrism(),
		Range:   MakeReadFileArgsRangeRefPrism(),
		Name:    MakeReadFileArgsNameRefPrism(),
		Content: MakeReadFileArgsContentRefPrism(),
	}
}
