package session

// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

import (
	__iso_option "github.com/IBM/fp-go/v2/optics/iso/option"
	__lens "github.com/IBM/fp-go/v2/optics/lens"
	__lens_option "github.com/IBM/fp-go/v2/optics/lens/option"
	__prism "github.com/IBM/fp-go/v2/optics/prism"
	__option "github.com/IBM/fp-go/v2/option"
	"github.com/openai/openai-go/v3"
)

// SessionLenses provides [lenses] for accessing fields of [Session]
//
// [lenses]: __lens.Lens
type SessionLenses struct {
	// history is a [__lens.Lens] for the history field of [Session]
	history __lens.Lens[Session, History]
	// current is a [__lens.Lens] for the current field of [Session]
	current __lens.Lens[Session, openai.ChatCompletionNewParams]
	// usage is a [__lens.Lens] for the usage field of [Session]
	usage __lens.Lens[Session, openai.CompletionUsage]
	// iterations is a [__lens.Lens] for the iterations field of [Session]
	iterations __lens.Lens[Session, int]
	// iterationsO is a [__lens_option.LensO] for the iterations field of [Session], treating the zero value as absent
	iterationsO __lens_option.LensO[Session, int]
}

// SessionRefLenses provides [lenses] for accessing fields of [Session] via a pointer to [Session]
//
// [lenses]: __lens.Lens
type SessionRefLenses struct {
	// history is a [__lens.Lens] for the history field of [Session] via a pointer receiver
	history __lens.Lens[*Session, History]
	// current is a [__lens.Lens] for the current field of [Session] via a pointer receiver
	current __lens.Lens[*Session, openai.ChatCompletionNewParams]
	// usage is a [__lens.Lens] for the usage field of [Session] via a pointer receiver
	usage __lens.Lens[*Session, openai.CompletionUsage]
	// iterations is a [__lens.Lens] for the iterations field of [Session] via a pointer receiver
	iterations __lens.Lens[*Session, int]
	// iterationsO is a [__lens_option.LensO] for the iterations field of [Session] via a pointer receiver, treating the zero value as absent
	iterationsO __lens_option.LensO[*Session, int]
}

// SessionPrisms provides [prisms] for accessing fields of [Session]
//
// [prisms]: __prism.Prism
type SessionPrisms struct {
	// history is a [__prism.Prism] for the history field of [Session]
	history __prism.Prism[Session, History]
	// current is a [__prism.Prism] for the current field of [Session]
	current __prism.Prism[Session, openai.ChatCompletionNewParams]
	// usage is a [__prism.Prism] for the usage field of [Session]
	usage __prism.Prism[Session, openai.CompletionUsage]
	// iterations is a [__prism.Prism] for the iterations field of [Session]
	iterations __prism.Prism[Session, int]
}

// SessionRefPrisms provides [prisms] for accessing fields of [Session] via a pointer to [Session]
//
// [prisms]: __prism.Prism
type SessionRefPrisms struct {
	// history is a [__prism.Prism] for the history field of [Session] via a pointer receiver
	history __prism.Prism[*Session, History]
	// current is a [__prism.Prism] for the current field of [Session] via a pointer receiver
	current __prism.Prism[*Session, openai.ChatCompletionNewParams]
	// usage is a [__prism.Prism] for the usage field of [Session] via a pointer receiver
	usage __prism.Prism[*Session, openai.CompletionUsage]
	// iterations is a [__prism.Prism] for the iterations field of [Session] via a pointer receiver
	iterations __prism.Prism[*Session, int]
}

// MakeSessionhistoryLens returns a [__lens.Lens] for the history field of [Session]
func MakeSessionhistoryLens() __lens.Lens[Session, History] {
	return __lens.MakeLensWithName(
		func(s Session) History { return s.history },
		func(s Session, v History) Session { s.history = v; return s },
		"Session.history",
	)
}

// MakeSessioncurrentLens returns a [__lens.Lens] for the current field of [Session]
func MakeSessioncurrentLens() __lens.Lens[Session, openai.ChatCompletionNewParams] {
	return __lens.MakeLensWithName(
		func(s Session) openai.ChatCompletionNewParams { return s.current },
		func(s Session, v openai.ChatCompletionNewParams) Session { s.current = v; return s },
		"Session.current",
	)
}

// MakeSessioncurrentRefLens returns a [__lens.Lens] for the current field of [Session] via a pointer receiver
func MakeSessioncurrentRefLens() __lens.Lens[*Session, openai.ChatCompletionNewParams] {
	return __lens.MakeLensRefWithName(
		func(s *Session) openai.ChatCompletionNewParams { return s.current },
		func(s *Session, v openai.ChatCompletionNewParams) *Session { s.current = v; return s },
		"(*Session).current",
	)
}

// MakeSessioncurrentPrism returns a [__prism.Prism] for the current field of [Session]
func MakeSessioncurrentPrism() __prism.Prism[Session, openai.ChatCompletionNewParams] {
	return __prism.MakePrismWithName(
		func(s Session) __option.Option[openai.ChatCompletionNewParams] { return __option.Some(s.current) },
		func(v openai.ChatCompletionNewParams) Session {
			return Session{current: v}
		},
		"Session.current",
	)
}

// MakeSessioncurrentRefPrism returns a [__prism.Prism] for the current field of [Session] via a pointer receiver
func MakeSessioncurrentRefPrism() __prism.Prism[*Session, openai.ChatCompletionNewParams] {
	return __prism.MakePrismWithName(
		func(s *Session) __option.Option[openai.ChatCompletionNewParams] { return __option.Some(s.current) },
		func(v openai.ChatCompletionNewParams) *Session {
			return &Session{current: v}
		},
		"Session.current",
	)
}

// MakeSessionusageLens returns a [__lens.Lens] for the usage field of [Session]
func MakeSessionusageLens() __lens.Lens[Session, openai.CompletionUsage] {
	return __lens.MakeLensWithName(
		func(s Session) openai.CompletionUsage { return s.usage },
		func(s Session, v openai.CompletionUsage) Session { s.usage = v; return s },
		"Session.usage",
	)
}

// MakeSessionusageRefLens returns a [__lens.Lens] for the usage field of [Session] via a pointer receiver
func MakeSessionusageRefLens() __lens.Lens[*Session, openai.CompletionUsage] {
	return __lens.MakeLensRefWithName(
		func(s *Session) openai.CompletionUsage { return s.usage },
		func(s *Session, v openai.CompletionUsage) *Session { s.usage = v; return s },
		"(*Session).usage",
	)
}

// MakeSessionusagePrism returns a [__prism.Prism] for the usage field of [Session]
func MakeSessionusagePrism() __prism.Prism[Session, openai.CompletionUsage] {
	return __prism.MakePrismWithName(
		func(s Session) __option.Option[openai.CompletionUsage] { return __option.Some(s.usage) },
		func(v openai.CompletionUsage) Session {
			return Session{usage: v}
		},
		"Session.usage",
	)
}

// MakeSessionusageRefPrism returns a [__prism.Prism] for the usage field of [Session] via a pointer receiver
func MakeSessionusageRefPrism() __prism.Prism[*Session, openai.CompletionUsage] {
	return __prism.MakePrismWithName(
		func(s *Session) __option.Option[openai.CompletionUsage] { return __option.Some(s.usage) },
		func(v openai.CompletionUsage) *Session {
			return &Session{usage: v}
		},
		"Session.usage",
	)
}

// MakeSessioniterationsLens returns a [__lens.Lens] for the iterations field of [Session]
func MakeSessioniterationsLens() __lens.Lens[Session, int] {
	return __lens.MakeLensWithName(
		func(s Session) int { return s.iterations },
		func(s Session, v int) Session { s.iterations = v; return s },
		"Session.iterations",
	)
}

// MakeSessioniterationsLensO returns a [__lens_option.LensO] for the iterations field of [Session]
func MakeSessioniterationsLensO() __lens_option.LensO[Session, int] {
	return __lens_option.FromIso[Session](__iso_option.FromZero[int]())(MakeSessioniterationsLens())
}

// MakeSessioniterationsRefLens returns a [__lens.Lens] for the iterations field of [Session] via a pointer receiver
func MakeSessioniterationsRefLens() __lens.Lens[*Session, int] {
	return __lens.MakeLensStrictWithName(
		func(s *Session) int { return s.iterations },
		func(s *Session, v int) *Session { s.iterations = v; return s },
		"(*Session).iterations",
	)
}

// MakeSessioniterationsRefLensO returns a [__lens_option.LensO] for the iterations field of [Session] via a pointer receiver
func MakeSessioniterationsRefLensO() __lens_option.LensO[*Session, int] {
	return __lens_option.FromIso[*Session](__iso_option.FromZero[int]())(MakeSessioniterationsRefLens())
}

// MakeSessioniterationsPrism returns a [__prism.Prism] for the iterations field of [Session]
func MakeSessioniterationsPrism() __prism.Prism[Session, int] {
	_fromNonZero := __option.FromNonZero[int]()
	return __prism.MakePrismWithName(
		func(s Session) __option.Option[int] { return _fromNonZero(s.iterations) },
		func(v int) Session {
			return Session{iterations: v}
		},
		"Session.iterations",
	)
}

// MakeSessioniterationsRefPrism returns a [__prism.Prism] for the iterations field of [Session] via a pointer receiver
func MakeSessioniterationsRefPrism() __prism.Prism[*Session, int] {
	_fromNonZero := __option.FromNonZero[int]()
	return __prism.MakePrismWithName(
		func(s *Session) __option.Option[int] { return _fromNonZero(s.iterations) },
		func(v int) *Session {
			return &Session{iterations: v}
		},
		"Session.iterations",
	)
}

// MakeSessionLenses creates a new [SessionLenses] with [lenses] for all fields
//
// [lenses]: __lens.Lens
func MakeSessionLenses() SessionLenses {
	return SessionLenses{
		// mandatory lenses
		history:    MakeSessionhistoryLens(),
		current:    MakeSessioncurrentLens(),
		usage:      MakeSessionusageLens(),
		iterations: MakeSessioniterationsLens(),
		// optional lenses
		iterationsO: MakeSessioniterationsLensO(),
	}
}

// MakeSessionRefLenses creates a new [SessionRefLenses] with [lenses] for all fields via a pointer to [Session]
//
// [lenses]: __lens.Lens
func MakeSessionRefLenses() SessionRefLenses {
	return SessionRefLenses{
		// mandatory lenses
		current:    MakeSessioncurrentRefLens(),
		usage:      MakeSessionusageRefLens(),
		iterations: MakeSessioniterationsRefLens(),
		// optional lenses
		iterationsO: MakeSessioniterationsRefLensO(),
	}
}

// MakeSessionPrisms creates a new [SessionPrisms] with [prisms] for all fields
//
// [prisms]: __prism.Prism
func MakeSessionPrisms() SessionPrisms {
	return SessionPrisms{
		current:    MakeSessioncurrentPrism(),
		usage:      MakeSessionusagePrism(),
		iterations: MakeSessioniterationsPrism(),
	}
}

// MakeSessionRefPrisms creates a new [SessionRefPrisms] with [prisms] for all fields via a pointer to [Session]
//
// [prisms]: __prism.Prism
func MakeSessionRefPrisms() SessionRefPrisms {
	return SessionRefPrisms{
		current:    MakeSessioncurrentRefPrism(),
		usage:      MakeSessionusageRefPrism(),
		iterations: MakeSessioniterationsRefPrism(),
	}
}
